//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DivingTracker.ServiceLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.Users = new HashSet<User>();
        }
    
        public int BranchId { get; set; }
        public int AgencyId { get; set; }
        public Nullable<int> ChairUserId { get; set; }
        public Nullable<int> SecretaryUserId { get; set; }
        public Nullable<int> TreasurerUserId { get; set; }
        public Nullable<int> DivingOfficerUserId { get; set; }
        public Nullable<int> ContactAddressId { get; set; }
        public Nullable<int> PoolAddressId { get; set; }
        public string ContactEmail { get; set; }
        public string ContactLandLine { get; set; }
        public string ContactMobile { get; set; }
    
        public virtual Address BranchAddress { get; set; }
        public virtual Address PoolAddress { get; set; }
        public virtual Agency Agency { get; set; }
        public virtual User BranchChair { get; set; }
        public virtual User BranchDivingOfficer { get; set; }
        public virtual User BranchSecretary { get; set; }
        public virtual User BranchTreasurer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
