//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DivingTracker.ServiceLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCriterion
    {
        public int UserCriterionId { get; set; }
        public int UserId { get; set; }
        public int CriterionId { get; set; }
        public Nullable<int> CriterionStatusId { get; set; }
        public Nullable<int> AwardedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Criterion Criterion { get; set; }
        public virtual CriterionStatus CriterionStatus { get; set; }
        public virtual User AwardedByUser { get; set; }
        public virtual User User { get; set; }
    }
}
